import numpy as np
from typing import Dict, Any
from api.models.survey import Question, QuestionType

def generate_structured(persona: Dict[str, Any], question: Question, context: Dict[str, Any]) -> Any:
    """
    Generate a realistic answer for a question based on respondent persona and context.
    """
    q_type = question.type
    
    if q_type == QuestionType.rating:
        # Sample rating from a normal distribution around the persona's sat_mean
        scale = question.scale or 5
        mean = persona["sat_mean"]
        std = persona["sat_std"]
        
        # Adjust satisfaction further if delivery was late
        if not persona["delivery_on_time"]:
            # Drop satisfaction mean if delivery was late
            mean = max(1.0, mean - 1.5)
            
        val = np.random.normal(mean, std)
        val = int(np.round(val))
        val = max(1, min(scale, val))
        return val
        
    elif q_type == QuestionType.nps:
        # NPS should have r > 0.7 correlation with overall satisfaction rating (usually first rating in context)
        scale = question.scale or 10
        
        # Find first rating value in context
        sat_val = None
        for key, val in context.items():
            # If the context value is an integer and likely a rating
            if isinstance(val, int) and val <= 5:
                sat_val = val
                break
                
        if sat_val is None:
            # Fallback if no satisfaction rating generated yet
            mean = persona["sat_mean"]
            sat_val = int(np.round(np.random.normal(mean, persona["sat_std"])))
            sat_val = max(1, min(5, sat_val))
            
        # Map 1-5 satisfaction to 0-10 NPS scale:
        # 1 -> 0 or 1, 2 -> 3 or 4, 3 -> 6, 4 -> 8, 5 -> 10
        nps_map = {1: 1.0, 2: 3.5, 3: 6.0, 4: 8.5, 5: 10.0}
        nps_base = nps_map.get(sat_val, 6.0)
        
        # Add persona boost and random noise
        boost = persona["nps_boost"]
        noise = np.random.normal(0, 0.8)
        
        nps_val = nps_base + boost + noise
        nps_val = int(np.round(nps_val))
        nps_val = max(0, min(scale, nps_val))
        return nps_val
        
    elif q_type == QuestionType.single_choice:
        options = question.options or []
        if not options:
            return ""
            
        q_id_lower = question.id.lower()
        q_text_lower = question.text.lower()
        
        # Check if this is the delivery question (on-time or late)
        is_delivery = "delivery" in q_id_lower or "delivery" in q_text_lower or "on time" in q_text_lower or "arrive" in q_text_lower
        
        if is_delivery:
            # Match options to Yes/No
            yes_option = next((o for o in options if o.lower() in ["yes", "on time", "on-time", "true"]), options[0])
            no_option = next((o for o in options if o.lower() in ["no", "late", "delayed", "false"]), options[-1] if len(options) > 1 else options[0])
            
            return yes_option if persona["delivery_on_time"] else no_option
            
        # Check if this is the category question
        is_category = "category" in q_id_lower or "category" in q_text_lower or "product type" in q_text_lower or "department" in q_text_lower
        
        if is_category:
            # Try to match the persona's pre-assigned category with options
            matched_option = next((o for o in options if o.lower() == persona["category"].lower()), None)
            if matched_option:
                return matched_option
                
        # Fallback to random choice
        return np.random.choice(options)
        
    elif q_type == QuestionType.open_text:
        # Open text generated by Cohere or fallback templates in a later phase
        return None
        
    return None
